"""Create relationship between - Imovel/Interessados

Revision ID: 81fdcd43fbab
Revises: f357dec3eff3
Create Date: 2026-05-15 21:03:35.156337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81fdcd43fbab'
down_revision: Union[str, Sequence[str], None] = 'f357dec3eff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interessados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('estado', sa.Integer(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=False),
    sa.Column('imovel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['estado'], ['estados.id'], ),
    sa.ForeignKeyConstraint(['imovel_id'], ['imoveis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interessados')
    # ### end Alembic commands ###
