"""Create table fotos

Revision ID: 872fd322ef48
Revises: b6ff978c1437
Create Date: 2026-05-11 19:05:31.969865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '872fd322ef48'
down_revision: Union[str, Sequence[str], None] = 'b6ff978c1437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fotos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('caminho', sa.String(), nullable=False),
    sa.Column('imovel', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['imovel'], ['imoveis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fotos')
    # ### end Alembic commands ###
