"""create relationship between imovel and foto

Revision ID: 9ad83b7614eb
Revises: f21f9e77d5e3
Create Date: 2026-05-15 20:11:11.636079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ad83b7614eb'
down_revision: Union[str, Sequence[str], None] = 'f21f9e77d5e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fotos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caminho', sa.String(), nullable=False),
    sa.Column('imovel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['imovel_id'], ['imoveis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fotos')
    # ### end Alembic commands ###
