"""Create table Configs-whatsapp

Revision ID: b83ca87e1864
Revises: e153d24ef4a2
Create Date: 2026-06-18 14:32:30.906245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b83ca87e1864'
down_revision: Union[str, Sequence[str], None] = 'e153d24ef4a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configs_whatsapp',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('mensagem', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configs_whatsapp')
    # ### end Alembic commands ###
