"""Create column mensagem in table interessados

Revision ID: e153d24ef4a2
Revises: 0c4e87e7a4b1
Create Date: 2026-06-17 11:25:51.515677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e153d24ef4a2'
down_revision: Union[str, Sequence[str], None] = '0c4e87e7a4b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interessados', sa.Column('mensagem', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interessados', 'mensagem')
    # ### end Alembic commands ###
