"""Create tables

Revision ID: f21f9e77d5e3
Revises: 
Create Date: 2026-05-12 21:54:21.002752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f21f9e77d5e3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caracteristicas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estados',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finalidades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pretensoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipos_imovel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imoveis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('lancamento', sa.Boolean(), nullable=True),
    sa.Column('destaque', sa.Boolean(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('visualizacoes', sa.Integer(), nullable=True),
    sa.Column('finalidade', sa.Integer(), nullable=True),
    sa.Column('tipo_imovel', sa.Integer(), nullable=True),
    sa.Column('pretensao', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Integer(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('complemento', sa.String(), nullable=True),
    sa.Column('sobre_imovel', sa.String(), nullable=True),
    sa.Column('area_total', sa.Float(), nullable=True),
    sa.Column('area_construida', sa.Float(), nullable=True),
    sa.Column('dormitorios', sa.Integer(), nullable=True),
    sa.Column('banheiros', sa.Integer(), nullable=True),
    sa.Column('suites', sa.Integer(), nullable=True),
    sa.Column('vagas_garagem', sa.Integer(), nullable=True),
    sa.Column('vagas_garagem_cobertas', sa.Integer(), nullable=True),
    sa.Column('vagas_garagem_descobertas', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['estado'], ['estados.id'], ),
    sa.ForeignKeyConstraint(['finalidade'], ['finalidades.id'], ),
    sa.ForeignKeyConstraint(['pretensao'], ['pretensoes.id'], ),
    sa.ForeignKeyConstraint(['tipo_imovel'], ['tipos_imovel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('caracteristica_imovel_association',
    sa.Column('caracteristica_id', sa.Integer(), nullable=False),
    sa.Column('imovel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['caracteristica_id'], ['caracteristicas.id'], ),
    sa.ForeignKeyConstraint(['imovel_id'], ['imoveis.id'], ),
    sa.PrimaryKeyConstraint('caracteristica_id', 'imovel_id')
    )
    op.create_table('comentarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('texto', sa.String(), nullable=False),
    sa.Column('aprovado', sa.Boolean(), nullable=False),
    sa.Column('imovel', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['imovel'], ['imoveis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fotos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('caminho', sa.String(), nullable=False),
    sa.Column('imovel', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['imovel'], ['imoveis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interessados',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('estado', sa.Integer(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=False),
    sa.Column('imovel', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['estado'], ['estados.id'], ),
    sa.ForeignKeyConstraint(['imovel'], ['imoveis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interessados')
    op.drop_table('fotos')
    op.drop_table('comentarios')
    op.drop_table('caracteristica_imovel_association')
    op.drop_table('imoveis')
    op.drop_table('tipos_imovel')
    op.drop_table('pretensoes')
    op.drop_table('finalidades')
    op.drop_table('estados')
    op.drop_table('caracteristicas')
    # ### end Alembic commands ###
