"""Create relationship between Imovel and Comentarios

Revision ID: f357dec3eff3
Revises: 9ad83b7614eb
Create Date: 2026-05-15 20:58:36.253194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f357dec3eff3'
down_revision: Union[str, Sequence[str], None] = '9ad83b7614eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(), nullable=False),
    sa.Column('aprovado', sa.Boolean(), nullable=False),
    sa.Column('imovel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['imovel_id'], ['imoveis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comentarios')
    # ### end Alembic commands ###
