"""Create columns localizacao in imovel

Revision ID: f5ac06634b13
Revises: b83ca87e1864
Create Date: 2026-06-20 16:43:23.573684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5ac06634b13'
down_revision: Union[str, Sequence[str], None] = 'b83ca87e1864'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imoveis', sa.Column('localizacao_desc', sa.String(), nullable=True))
    op.add_column('imoveis', sa.Column('localizacao_img', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('imoveis', 'localizacao_img')
    op.drop_column('imoveis', 'localizacao_desc')
    # ### end Alembic commands ###
